type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run 01-00 Master Finance Reporting Orchestration"
      parameters:
        componentName: "Start"
    Run 01-00 Master Finance Reporting Orchestration:
      type: "run-orchestration"
      parameters:
        componentName: "Run 01-00 Master Finance Reporting Orchestration"
        orchestrationJob: "01 - Finance/01-00 Master Finance Reporting Orchestration"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: -40
        "y": 10
      tempMetlId: 1
    Run 01-00 Master Finance Reporting Orchestration:
      position:
        x: 100
        "y": 10
      tempMetlId: 2
