type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Run 01-10 Orders Reporting"
        - "Run 01-20 Customer Loyalty Reporting"
        - "Run 01-30 Truck Reporting"
      parameters:
        componentName: "Start"
    Run 01-10 Orders Reporting:
      type: "run-transformation"
      parameters:
        componentName: "Run 01-10 Orders Reporting"
        transformationJob: "01 - Finance/01-10 Orders Reporting"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateScalarVariables:
    Run 01-20 Customer Loyalty Reporting:
      type: "run-transformation"
      parameters:
        componentName: "Run 01-20 Customer Loyalty Reporting"
        transformationJob: "01 - Finance/01-20 Customer Loyalty Reporting"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateScalarVariables:
    Run 01-30 Truck Reporting:
      type: "run-transformation"
      parameters:
        componentName: "Run 01-30 Truck Reporting"
        transformationJob: "01 - Finance/01-30 Truck Reporting"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 20
        "y": 30
      tempMetlId: 1
    Run 01-10 Orders Reporting:
      position:
        x: 240
        "y": -70
      tempMetlId: 7
    Run 01-20 Customer Loyalty Reporting:
      position:
        x: 240
        "y": 30
      tempMetlId: 8
    Run 01-30 Truck Reporting:
      position:
        x: 240
        "y": 130
      tempMetlId: 9
